name: py36_ff
# NOTE: Uncomment lines if installing for GPU system.
channels:
  - defaults
dependencies:
  # - cudatoolkit=10.0.130
  # - cudnn=7.6.5
  - jupyterlab=3.1.7
  - matplotlib=3.3.4
  - notebook=6.4.3
  - python=3.6.13
  - pytorch=1.3.1
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - seaborn=0.11.2
  - pip:
    - numpy==1.18.5
    - tensorflow==1.15.5
    # - tensorflow-gpu==1.15.5
